; ModuleID = '/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/rglobals.c'
source_filename = "/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/rglobals.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@tempArray = common dso_local local_unnamed_addr global ptr null, align 8
@gnodeArray = common dso_local local_unnamed_addr global ptr null, align 8
@pnodeArray = common dso_local local_unnamed_addr global ptr null, align 8
@numnodes = common dso_local local_unnamed_addr global i32 0, align 4
@numpins = common dso_local local_unnamed_addr global i32 0, align 4
@maxpnode = common dso_local local_unnamed_addr global i32 0, align 4
@pnameArray = common dso_local local_unnamed_addr global ptr null, align 8
@nnameArray = common dso_local local_unnamed_addr global ptr null, align 8
@pinOffset = common dso_local local_unnamed_addr global ptr null, align 8
@pinlist = common dso_local local_unnamed_addr global ptr null, align 8
@pathList = common dso_local local_unnamed_addr global ptr null, align 8
@netSegArray = common dso_local local_unnamed_addr global ptr null, align 8
@segList = common dso_local local_unnamed_addr global ptr null, align 8
@segPtr = common dso_local local_unnamed_addr global i32 0, align 4
@sourceList = common dso_local local_unnamed_addr global ptr null, align 8
@sourcePtr = common dso_local local_unnamed_addr global i32 0, align 4
@targetList = common dso_local local_unnamed_addr global ptr null, align 8
@targetPtr = common dso_local local_unnamed_addr global i32 0, align 4
@Mpaths = common dso_local local_unnamed_addr global i32 0, align 4
@delSourceList = common dso_local local_unnamed_addr global ptr null, align 8
@addTargetList = common dso_local local_unnamed_addr global ptr null, align 8
@pathLength = common dso_local local_unnamed_addr global i32 0, align 4
@savePaths = common dso_local local_unnamed_addr global ptr null, align 8
@largestNet = common dso_local local_unnamed_addr global i32 0, align 4
@netRoutes = common dso_local local_unnamed_addr global ptr null, align 8
@gtrace = common dso_local local_unnamed_addr global ptr null, align 8
@pathArray = common dso_local local_unnamed_addr global ptr null, align 8
@MAXPATHS = common dso_local local_unnamed_addr global i32 0, align 4
@EXTRASOURCES = common dso_local local_unnamed_addr global i32 0, align 4

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 17.0.0"}
