; ModuleID = '/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/mafft/defs.c'
source_filename = "/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/mafft/defs.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@commonAlloc1 = dso_local local_unnamed_addr global i32 0, align 4
@commonAlloc2 = dso_local local_unnamed_addr global i32 0, align 4
@commonIP = dso_local local_unnamed_addr global ptr null, align 8
@commonJP = dso_local local_unnamed_addr global ptr null, align 8
@consweight_multi = dso_local local_unnamed_addr global float 1.000000e+00, align 4
@consweight_rna = dso_local local_unnamed_addr global float 0.000000e+00, align 4
@RNAscoremtx = dso_local local_unnamed_addr global i8 110, align 1
@modelname = dso_local local_unnamed_addr global [100 x i8] zeroinitializer, align 16
@njob = dso_local local_unnamed_addr global i32 0, align 4
@nlenmax = dso_local local_unnamed_addr global i32 0, align 4
@amino_n = dso_local local_unnamed_addr global [128 x i32] zeroinitializer, align 16
@amino_grp = dso_local local_unnamed_addr global [128 x i8] zeroinitializer, align 16
@amino_dis = dso_local local_unnamed_addr global [128 x [128 x i32]] zeroinitializer, align 16
@amino_disLN = dso_local local_unnamed_addr global [128 x [128 x i32]] zeroinitializer, align 16
@amino_dis_consweight_multi = dso_local local_unnamed_addr global [128 x [128 x double]] zeroinitializer, align 16
@n_dis = dso_local local_unnamed_addr global [26 x [26 x i32]] zeroinitializer, align 16
@n_disFFT = dso_local local_unnamed_addr global [26 x [26 x i32]] zeroinitializer, align 16
@n_dis_consweight_multi = dso_local local_unnamed_addr global [26 x [26 x float]] zeroinitializer, align 16
@amino = dso_local local_unnamed_addr global [26 x i8] zeroinitializer, align 16
@polarity = dso_local local_unnamed_addr global [20 x double] zeroinitializer, align 16
@volume = dso_local local_unnamed_addr global [20 x double] zeroinitializer, align 16
@ribosumdis = dso_local local_unnamed_addr global [37 x [37 x i32]] zeroinitializer, align 16
@ppid = dso_local local_unnamed_addr global i32 0, align 4
@thrinter = dso_local local_unnamed_addr global double 0.000000e+00, align 8
@fastathreshold = dso_local local_unnamed_addr global double 0.000000e+00, align 8
@pslocal = dso_local local_unnamed_addr global i32 0, align 4
@ppslocal = dso_local local_unnamed_addr global i32 0, align 4
@constraint = dso_local local_unnamed_addr global i32 0, align 4
@divpairscore = dso_local local_unnamed_addr global i32 0, align 4
@fmodel = dso_local local_unnamed_addr global i32 0, align 4
@nblosum = dso_local local_unnamed_addr global i32 0, align 4
@kobetsubunkatsu = dso_local local_unnamed_addr global i32 0, align 4
@bunkatsu = dso_local local_unnamed_addr global i32 0, align 4
@dorp = dso_local local_unnamed_addr global i32 0, align 4
@niter = dso_local local_unnamed_addr global i32 0, align 4
@contin = dso_local local_unnamed_addr global i32 0, align 4
@calledByXced = dso_local local_unnamed_addr global i32 0, align 4
@devide = dso_local local_unnamed_addr global i32 0, align 4
@scmtd = dso_local local_unnamed_addr global i32 0, align 4
@weight = dso_local local_unnamed_addr global i32 0, align 4
@utree = dso_local local_unnamed_addr global i32 0, align 4
@tbutree = dso_local local_unnamed_addr global i32 0, align 4
@refine = dso_local local_unnamed_addr global i32 0, align 4
@check = dso_local local_unnamed_addr global i32 0, align 4
@cut = dso_local local_unnamed_addr global double 0.000000e+00, align 8
@cooling = dso_local local_unnamed_addr global i32 0, align 4
@penalty = dso_local local_unnamed_addr global i32 0, align 4
@ppenalty = dso_local local_unnamed_addr global i32 0, align 4
@penaltyLN = dso_local local_unnamed_addr global i32 0, align 4
@RNApenalty = dso_local local_unnamed_addr global i32 0, align 4
@RNAppenalty = dso_local local_unnamed_addr global i32 0, align 4
@RNApenalty_ex = dso_local local_unnamed_addr global i32 0, align 4
@RNAppenalty_ex = dso_local local_unnamed_addr global i32 0, align 4
@penalty_ex = dso_local local_unnamed_addr global i32 0, align 4
@ppenalty_ex = dso_local local_unnamed_addr global i32 0, align 4
@penalty_exLN = dso_local local_unnamed_addr global i32 0, align 4
@penalty_EX = dso_local local_unnamed_addr global i32 0, align 4
@ppenalty_EX = dso_local local_unnamed_addr global i32 0, align 4
@penalty_OP = dso_local local_unnamed_addr global i32 0, align 4
@ppenalty_OP = dso_local local_unnamed_addr global i32 0, align 4
@RNAthr = dso_local local_unnamed_addr global i32 0, align 4
@RNApthr = dso_local local_unnamed_addr global i32 0, align 4
@offset = dso_local local_unnamed_addr global i32 0, align 4
@poffset = dso_local local_unnamed_addr global i32 0, align 4
@offsetLN = dso_local local_unnamed_addr global i32 0, align 4
@offsetFFT = dso_local local_unnamed_addr global i32 0, align 4
@scoremtx = dso_local local_unnamed_addr global i32 0, align 4
@TMorJTT = dso_local local_unnamed_addr global i32 0, align 4
@use_fft = dso_local local_unnamed_addr global i8 0, align 1
@force_fft = dso_local local_unnamed_addr global i8 0, align 1
@nevermemsave = dso_local local_unnamed_addr global i32 0, align 4
@fftscore = dso_local local_unnamed_addr global i32 0, align 4
@fftWinSize = dso_local local_unnamed_addr global i32 0, align 4
@fftThreshold = dso_local local_unnamed_addr global i32 0, align 4
@fftRepeatStop = dso_local local_unnamed_addr global i32 0, align 4
@fftNoAnchStop = dso_local local_unnamed_addr global i32 0, align 4
@divWinSize = dso_local local_unnamed_addr global i32 0, align 4
@divThreshold = dso_local local_unnamed_addr global i32 0, align 4
@disp = dso_local local_unnamed_addr global i32 0, align 4
@outgap = dso_local local_unnamed_addr global i32 0, align 4
@alg = dso_local local_unnamed_addr global i8 0, align 1
@cnst = dso_local local_unnamed_addr global i32 0, align 4
@mix = dso_local local_unnamed_addr global i32 0, align 4
@tbitr = dso_local local_unnamed_addr global i32 0, align 4
@tbweight = dso_local local_unnamed_addr global i32 0, align 4
@tbrweight = dso_local local_unnamed_addr global i32 0, align 4
@disopt = dso_local local_unnamed_addr global i32 0, align 4
@pamN = dso_local local_unnamed_addr global i32 0, align 4
@checkC = dso_local local_unnamed_addr global i32 0, align 4
@geta2 = dso_local local_unnamed_addr global float 0.000000e+00, align 4
@treemethod = dso_local local_unnamed_addr global i32 0, align 4
@kimuraR = dso_local local_unnamed_addr global i32 0, align 4
@swopt = dso_local local_unnamed_addr global ptr null, align 8
@fftkeika = dso_local local_unnamed_addr global i32 0, align 4
@score_check = dso_local local_unnamed_addr global i32 0, align 4
@makedistmtx = dso_local local_unnamed_addr global i32 0, align 4
@inputfile = dso_local local_unnamed_addr global ptr null, align 8
@rnakozo = dso_local local_unnamed_addr global i32 0, align 4
@rnaprediction = dso_local local_unnamed_addr global i8 0, align 1
@signalSM = dso_local local_unnamed_addr global ptr null, align 8
@prep_g = dso_local local_unnamed_addr global ptr null, align 8
@trap_g = dso_local local_unnamed_addr global ptr null, align 8
@seq_g = dso_local local_unnamed_addr global ptr null, align 8
@res_g = dso_local local_unnamed_addr global ptr null, align 8

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 17.0.0"}
