; ModuleID = '/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/globals.c'
source_filename = "/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/globals.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@cellarray = common dso_local local_unnamed_addr global ptr null, align 8
@netarray = common dso_local local_unnamed_addr global ptr null, align 8
@termarray = common dso_local local_unnamed_addr global ptr null, align 8
@blockarray = common dso_local local_unnamed_addr global ptr null, align 8
@bdxlength = common dso_local local_unnamed_addr global i32 0, align 4
@bdylength = common dso_local local_unnamed_addr global i32 0, align 4
@blockl = common dso_local local_unnamed_addr global i32 0, align 4
@blockr = common dso_local local_unnamed_addr global i32 0, align 4
@blockt = common dso_local local_unnamed_addr global i32 0, align 4
@blockb = common dso_local local_unnamed_addr global i32 0, align 4
@blockmx = common dso_local local_unnamed_addr global i32 0, align 4
@blockmy = common dso_local local_unnamed_addr global i32 0, align 4
@numcells = common dso_local local_unnamed_addr global i32 0, align 4
@numpads = common dso_local local_unnamed_addr global i32 0, align 4
@numBinsX = common dso_local local_unnamed_addr global i32 0, align 4
@numBinsY = common dso_local local_unnamed_addr global i32 0, align 4
@binWidthX = common dso_local local_unnamed_addr global i32 0, align 4
@binWidthY = common dso_local local_unnamed_addr global i32 0, align 4
@binOffsetX = common dso_local local_unnamed_addr global i32 0, align 4
@binOffsetY = common dso_local local_unnamed_addr global i32 0, align 4
@bucket = common dso_local local_unnamed_addr global ptr null, align 8
@maxWeight = common dso_local local_unnamed_addr global i32 0, align 4
@baseWeight = common dso_local local_unnamed_addr global i32 0, align 4
@slopeX = common dso_local local_unnamed_addr global double 0.000000e+00, align 8
@slopeY = common dso_local local_unnamed_addr global double 0.000000e+00, align 8
@basefactor = common dso_local local_unnamed_addr global double 0.000000e+00, align 8
@aveChanWid = common dso_local local_unnamed_addr global i32 0, align 4
@penalty = common dso_local local_unnamed_addr global i32 0, align 4
@funccost = common dso_local local_unnamed_addr global i32 0, align 4
@offset = common dso_local local_unnamed_addr global i32 0, align 4
@overfill = common dso_local local_unnamed_addr global i32 0, align 4
@hashtab = common dso_local local_unnamed_addr global ptr null, align 8
@netctr = common dso_local local_unnamed_addr global i32 0, align 4
@T = common dso_local local_unnamed_addr global double 0.000000e+00, align 8
@randVar = common dso_local local_unnamed_addr global i32 0, align 4
@fpo = common dso_local local_unnamed_addr global ptr null, align 8
@pinnames = common dso_local local_unnamed_addr global ptr null, align 8
@cktName = common dso_local local_unnamed_addr global ptr null, align 8
@maxterm = common dso_local local_unnamed_addr global i32 0, align 4
@numnets = common dso_local local_unnamed_addr global i32 0, align 4
@attmax = common dso_local local_unnamed_addr global i32 0, align 4
@occa1ptr = common dso_local local_unnamed_addr global ptr null, align 8
@occa2ptr = common dso_local local_unnamed_addr global ptr null, align 8
@occb1ptr = common dso_local local_unnamed_addr global ptr null, align 8
@occb2ptr = common dso_local local_unnamed_addr global ptr null, align 8
@binX = common dso_local local_unnamed_addr global i32 0, align 4
@binY = common dso_local local_unnamed_addr global i32 0, align 4
@pinsPerLen = common dso_local local_unnamed_addr global double 0.000000e+00, align 8
@pSideArray = common dso_local local_unnamed_addr global ptr null, align 8
@trackspacing = common dso_local local_unnamed_addr global i32 0, align 4
@pinSpacing = common dso_local local_unnamed_addr global i32 0, align 4
@lapFactor = common dso_local local_unnamed_addr global double 0.000000e+00, align 8
@overlap = common dso_local local_unnamed_addr global ptr null, align 8
@overlapf = common dso_local local_unnamed_addr global ptr null, align 8
@overlapx = common dso_local local_unnamed_addr global ptr null, align 8
@gOffsetX = common dso_local local_unnamed_addr global i32 0, align 4
@gOffsetY = common dso_local local_unnamed_addr global i32 0, align 4
@gridX = common dso_local local_unnamed_addr global i32 0, align 4
@gridY = common dso_local local_unnamed_addr global i32 0, align 4
@coreGiven = common dso_local local_unnamed_addr global i32 0, align 4
@gridGiven = common dso_local local_unnamed_addr global i32 0, align 4
@layersFactor = common dso_local local_unnamed_addr global i32 0, align 4

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 17.0.0"}
