; ModuleID = '/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/unix-tbl/t0.c'
source_filename = "/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/unix-tbl/t0.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@expflg = dso_local local_unnamed_addr global i32 0, align 4
@ctrflg = dso_local local_unnamed_addr global i32 0, align 4
@boxflg = dso_local local_unnamed_addr global i32 0, align 4
@dboxflg = dso_local local_unnamed_addr global i32 0, align 4
@tab = dso_local local_unnamed_addr global i32 9, align 4
@F1 = dso_local local_unnamed_addr global i32 0, align 4
@F2 = dso_local local_unnamed_addr global i32 0, align 4
@allflg = dso_local local_unnamed_addr global i32 0, align 4
@leftover = dso_local local_unnamed_addr global i32 0, align 4
@textflg = dso_local local_unnamed_addr global i32 0, align 4
@left1flg = dso_local local_unnamed_addr global i32 0, align 4
@rightl = dso_local local_unnamed_addr global i32 0, align 4
@iline = dso_local local_unnamed_addr global i32 1, align 4
@.str = private unnamed_addr constant [6 x i8] c"Input\00", align 1
@ifile = dso_local local_unnamed_addr global ptr @.str, align 8
@texname = dso_local local_unnamed_addr global i32 97, align 4
@texct = dso_local local_unnamed_addr global i32 0, align 4
@texstr = dso_local local_unnamed_addr global [63 x i8] c"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWYXZ0123456789\00", align 16
@linsize = dso_local local_unnamed_addr global i32 0, align 4
@pr1403 = dso_local local_unnamed_addr global i32 0, align 4
@delim1 = dso_local local_unnamed_addr global i32 0, align 4
@delim2 = dso_local local_unnamed_addr global i32 0, align 4
@evenup = dso_local local_unnamed_addr global [20 x i32] zeroinitializer, align 16
@evenflg = dso_local local_unnamed_addr global i32 0, align 4
@cstore = dso_local local_unnamed_addr global ptr null, align 8
@cspace = dso_local local_unnamed_addr global ptr null, align 8
@last = dso_local local_unnamed_addr global ptr null, align 8
@table = dso_local local_unnamed_addr global [200 x ptr] zeroinitializer, align 16
@style = dso_local local_unnamed_addr global [100 x [20 x i32]] zeroinitializer, align 16
@ctop = dso_local local_unnamed_addr global [100 x [20 x i32]] zeroinitializer, align 16
@font = dso_local local_unnamed_addr global [100 x [20 x [2 x i8]]] zeroinitializer, align 16
@csize = dso_local local_unnamed_addr global [100 x [20 x [4 x i8]]] zeroinitializer, align 16
@vsize = dso_local local_unnamed_addr global [100 x [20 x [4 x i8]]] zeroinitializer, align 16
@lefline = dso_local local_unnamed_addr global [100 x [20 x i32]] zeroinitializer, align 16
@cll = dso_local local_unnamed_addr global [20 x [10 x i8]] zeroinitializer, align 16
@stynum = dso_local local_unnamed_addr global [201 x i32] zeroinitializer, align 16
@nslin = dso_local local_unnamed_addr global i32 0, align 4
@nclin = dso_local local_unnamed_addr global i32 0, align 4
@sep = dso_local local_unnamed_addr global [20 x i32] zeroinitializer, align 16
@fullbot = dso_local local_unnamed_addr global [200 x i32] zeroinitializer, align 16
@instead = dso_local local_unnamed_addr global [200 x ptr] zeroinitializer, align 16
@used = dso_local local_unnamed_addr global [20 x i32] zeroinitializer, align 16
@lused = dso_local local_unnamed_addr global [20 x i32] zeroinitializer, align 16
@rused = dso_local local_unnamed_addr global [20 x i32] zeroinitializer, align 16
@linestop = dso_local local_unnamed_addr global [200 x i32] zeroinitializer, align 16
@nlin = dso_local local_unnamed_addr global i32 0, align 4
@ncol = dso_local local_unnamed_addr global i32 0, align 4
@linstart = dso_local local_unnamed_addr global i32 0, align 4
@exstore = dso_local local_unnamed_addr global ptr null, align 8
@exlim = dso_local local_unnamed_addr global ptr null, align 8
@tabin = dso_local local_unnamed_addr global ptr null, align 8
@tabout = dso_local local_unnamed_addr global ptr null, align 8

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 17.0.0"}
