; ModuleID = '/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/gglobals.c'
source_filename = "/usr/local/google/home/aeubanks/repos/test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/gglobals.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@cellList = common dso_local local_unnamed_addr global ptr null, align 8
@pitch = common dso_local local_unnamed_addr global i32 0, align 4
@xBellArray = common dso_local local_unnamed_addr global ptr null, align 8
@yBellArray = common dso_local local_unnamed_addr global ptr null, align 8
@eIndexArray = common dso_local local_unnamed_addr global ptr null, align 8
@xNodeArray = common dso_local local_unnamed_addr global ptr null, align 8
@yNodeArray = common dso_local local_unnamed_addr global ptr null, align 8
@xNodules = common dso_local local_unnamed_addr global ptr null, align 8
@yNodules = common dso_local local_unnamed_addr global ptr null, align 8
@numXnodes = common dso_local local_unnamed_addr global i32 0, align 4
@numYnodes = common dso_local local_unnamed_addr global i32 0, align 4
@numberCells = common dso_local local_unnamed_addr global i32 0, align 4
@edgeTransition = common dso_local local_unnamed_addr global i32 0, align 4
@cktName = common dso_local local_unnamed_addr global ptr null, align 8
@VDroot = common dso_local local_unnamed_addr global ptr null, align 8
@HRroot = common dso_local local_unnamed_addr global ptr null, align 8
@LEroot = common dso_local local_unnamed_addr global ptr null, align 8
@BEroot = common dso_local local_unnamed_addr global ptr null, align 8
@Vroot = common dso_local local_unnamed_addr global ptr null, align 8
@Hroot = common dso_local local_unnamed_addr global ptr null, align 8
@vChanEndRoot = common dso_local local_unnamed_addr global ptr null, align 8
@vChanBeginRoot = common dso_local local_unnamed_addr global ptr null, align 8
@hChanEndRoot = common dso_local local_unnamed_addr global ptr null, align 8
@hChanBeginRoot = common dso_local local_unnamed_addr global ptr null, align 8
@LEptrs = common dso_local local_unnamed_addr global ptr null, align 8
@BEptrs = common dso_local local_unnamed_addr global ptr null, align 8
@VDptrs = common dso_local local_unnamed_addr global ptr null, align 8
@HRptrs = common dso_local local_unnamed_addr global ptr null, align 8
@Vptrs = common dso_local local_unnamed_addr global ptr null, align 8
@Hptrs = common dso_local local_unnamed_addr global ptr null, align 8
@eArray = common dso_local local_unnamed_addr global ptr null, align 8
@eNum = common dso_local local_unnamed_addr global i32 0, align 4
@rectArray = common dso_local local_unnamed_addr global ptr null, align 8
@numRects = common dso_local local_unnamed_addr global i32 0, align 4
@Hlist = common dso_local local_unnamed_addr global ptr null, align 8
@Vlist = common dso_local local_unnamed_addr global ptr null, align 8
@HRlist = common dso_local local_unnamed_addr global ptr null, align 8
@VRlist = common dso_local local_unnamed_addr global ptr null, align 8
@Hend = common dso_local local_unnamed_addr global ptr null, align 8
@Vend = common dso_local local_unnamed_addr global ptr null, align 8
@hFixedList = common dso_local local_unnamed_addr global ptr null, align 8
@vFixedList = common dso_local local_unnamed_addr global ptr null, align 8
@hFixedEnd = common dso_local local_unnamed_addr global ptr null, align 8
@vFixedEnd = common dso_local local_unnamed_addr global ptr null, align 8
@edgeList = common dso_local local_unnamed_addr global ptr null, align 8
@edgeCount = common dso_local local_unnamed_addr global i32 0, align 4
@numProbes = common dso_local local_unnamed_addr global i32 0, align 4
@hFixedEdgeRoot = common dso_local local_unnamed_addr global ptr null, align 8
@vFixedEdgeRoot = common dso_local local_unnamed_addr global ptr null, align 8
@hEdgeRoot = common dso_local local_unnamed_addr global ptr null, align 8
@vEdgeRoot = common dso_local local_unnamed_addr global ptr null, align 8
@hRectRoot = common dso_local local_unnamed_addr global ptr null, align 8
@vRectRoot = common dso_local local_unnamed_addr global ptr null, align 8
@bbl = common dso_local local_unnamed_addr global i32 0, align 4
@bbr = common dso_local local_unnamed_addr global i32 0, align 4
@bbb = common dso_local local_unnamed_addr global i32 0, align 4
@bbt = common dso_local local_unnamed_addr global i32 0, align 4
@fpdebug = common dso_local local_unnamed_addr global ptr null, align 8

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 17.0.0"}
